# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |_repo| 'https://github.com/#{repo}.git' }

ruby '2.6.4'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
end

group :development do
  gem 'debase', '~> 0.2.4'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'pry-rails', '~> 0.3.9'
  gem 'pry-theme', '~> 1.3'
  gem 'readapt', '~> 0.6.0'
  gem 'rubocop', '~> 0.74.0'
  gem 'rubocop-rails', '~> 2.3'
  gem 'ruby-debug-ide', '~> 0.7.0'
  gem 'solargraph', '~> 0.37.2'
  gem 'spring', '~> 2.1.0'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end

group :test do
  gem 'capybara', '>= 2.15' # system testing and selenium driver
  gem 'selenium-webdriver'
  gem 'webdrivers' # Easy installation and use of web drivers
end

gem 'bcrypt', '~> 3.1.7' # Use Active Model has_secure_password
gem 'bootsnap', '>= 1.4.2', require: false # required in config/boot.rb
gem 'faraday', '~> 0.15.4'
gem 'image_processing', '~> 1.2' # Use Active Storage variant
gem 'jbuilder', '~> 2.7' # https://github.com/rails/jbuilder
gem 'pg', '>= 0.18', '< 2.0' # Use postgresql as the database for Active Record
gem 'puma', '~> 3.11' # Use Puma as the app server
gem 'rails', '~> 6.0.0'
gem 'redis', '~> 4.0' # Use Redis adapter to run Action Cable in production
gem 'sass-rails', '~> 5' # Use SCSS for stylesheets
gem 'turbolinks', '~> 5' # https://github.com/turbolinks/turbolinks
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'webpacker', '~> 4.0' # https://github.com/rails/webpacker
