---
# Source: postgresql/templates/svc-read.yaml

apiVersion: v1
kind: Service
metadata:
  name: api-postgres-read
  labels:
    app: postgresql
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
  selector:
    app: postgresql
    role: slave
