---
# Source: postgresql/templates/secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: api-postgres
  labels:
    app: postgresql
type: Opaque
data:
  postgresql-password: "b24xbWFqZWVnN0VHaGF1V29oYmlvOUFlemVlcGFmMGk="
  postgresql-replication-password: "UGhveTlPZGFlcjlzaGVlaG9vN3F1aWVTaGFmNnllaTQ="
