---
apiVersion: v1
kind: Service
metadata:
  name: api-postgres-headless
  labels:
    app: api-postgres
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    app: api-postgres
