---
# Source: postgresql/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: api-postgres
  labels:
    app: postgresql
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
  selector:
    app: postgresql
    role: master
