---
# Source: redis/templates/metrics-svc.yaml

apiVersion: v1
kind: Service
metadata:
  name: api-redis-metrics
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9121
      targetPort: metrics
  selector:
    app: redis
