---
apiVersion: v1
kind: Service
metadata:
  name: db-postgres-metrics
  labels:
    app: db-postgres
  annotations:
    prometheus.io/port: "9187"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9187
      targetPort: metrics
  selector:
    app: db-postgres
    role: master
