---
kind: NetworkPolicy
apiVersion: "networking.k8s.io/v1"
metadata:
  name: db-postgres
  labels:
    app: db-postgres
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app: db-postgres
      role: master
  ingress:
    # Allow inbound connections
    - ports:
        - port: 5432
      from:
        - podSelector:
            matchLabels:
              db-postgres-client: "true"
        - podSelector:
            matchLabels:
              app: db-postgres
              role: slave
    # Allow prometheus scrapes
    - ports:
        - port: 9187
