---
apiVersion: v1
kind: Secret
metadata:
  name: db-postgres
  labels:
    app: db-postgres
type: Opaque
data:
  db-postgres-password: "b24xbWFqZWVnN0VHaGF1V29oYmlvOUFlemVlcGFmMGk="
  db-postgres-replication-password: "UGhveTlPZGFlcjlzaGVlaG9vN3F1aWVTaGFmNnllaTQ="
